GET http://127.0.0.1:2364/test/

###
GET http://127.0.0.1:2364/goods/

###
POST http://127.0.0.1:2364/test
Content-Type: application/json

{
    "param1": 1
}

###
PUT http://127.0.0.1:2364/

###
DELETE http://127.0.0.1:2364/